set-option -g mouse on
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -g mode-keys vi

set -g set-clipboard on
set -g @override_copy_command 'xclip -i -sel p -f | xclip -i -sel c'
set -g @yank_selection 'clipboard'
set-option -sa terminal-features ',*:clipboard'

# Detect environment and set the local copy command once
%if "#{==:#{XDG_SESSION_TYPE},wayland}"
    copy_cmd="wl-copy -p"
%else
    copy_cmd="xclip -in -sel primary"
%endif

# Word Select (Double Click)
bind-key -n DoubleClick1Pane copy-mode -M \; send-keys -X select-word \; send-keys -X copy-pipe-no-clear "$copy_cmd"
bind-key -T copy-mode-vi DoubleClick1Pane send-keys -X select-word \; send-keys -X copy-pipe-no-clear "$copy_cmd"

# Line Select (Triple Click)
bind-key -n TripleClick1Pane copy-mode -M \; send-keys -X select-line \; send-keys -X copy-pipe-no-clear "$copy_cmd"
bind-key -T copy-mode-vi TripleClick1Pane send-keys -X select-line \; send-keys -X copy-pipe-no-clear "$copy_cmd"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
