#!/bin/bash
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.\n"; exit 2; }
git lfs post-checkout "$@"

#checkout hook to locally set user name and email based on user defined patterns
#The patterns are matched against the clone url.
#
#Based on http://www.dvratil.cz/2015/12/git-trick-628-automatically-set-commit-author-based-on-repo-url/

function warn {
  echo -e "\n$1 not initialized in local config!"
}

http_proxy="$(git config --local http.proxy)"
https_proxy="$(git config --local https.proxy)"

host="$(hostname)"

if [[ ! -f ~/.git-clone-init ]]; then
cat << INPUT > ~/.git-clone-init
#!/bin/bash

case "$host" in
    * ) http_proxy=""; https_proxy="";;
esac
INPUT
  warn "\nMissing file ~/.git-clone-init. Template created..."
  exit 0
fi
. ~/.git-clone-init

if [[ -z $http_proxy ]]; then
  warn "Failed to detect proxy settings using ~/.git-clone-init. http_proxy and https_proxy"
  exit 0
fi

git config --local http.proxy "$http_proxy"
git config --local https.proxy "$https_proxy"

echo -e "http_proxy settings for ${PWD##*/} set to \"$http_proxy\""
echo -e "https_proxy settings for ${PWD##*/} set to \"$https_proxy\""
